"""add account status and transfer limit

Revision ID: 4fefb330dffe
Revises: d2cb0e2faabf
Create Date: 2026-08-29 20:48:18.903511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fefb330dffe'
down_revision: Union[str, Sequence[str], None] = 'd2cb0e2faabf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('bank_accounts', sa.Column('daily_transfer_limit', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('transactions', sa.Column('reference', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_transactions_reference'), 'transactions', ['reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_reference'), table_name='transactions')
    op.drop_column('transactions', 'reference')
    op.drop_column('bank_accounts', 'daily_transfer_limit')
    op.drop_column('bank_accounts', 'is_active')
    # ### end Alembic commands ###
