"""add audit logs

Revision ID: b2f5aa339e2b
Revises: 63c2317018df
Create Date: 2026-08-29 21:14:48.870767

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b2f5aa339e2b"
down_revision: str | Sequence[str] | None = "63c2317018df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
